#!/bin/sh

uci set luci.main.lang=zh_cn
uci commit luci

uci set system.@system[0].timezone=CST-8
uci set system.@system[0].zonename=Asia/Shanghai
uci commit system

# 禁止自动挂在，禁止匿名挂载.
#uci set fstab.@global[0].anon_mount=0
#uci set fstab.@global[0].auto_mount=0

# 启用匿名挂在，启用自动挂载.
uci set fstab.@global[0].anon_mount=1
uci set fstab.@global[0].auto_mount=1

uci commit fstab

rm -f /usr/lib/lua/luci/view/admin_status/index/mwan.htm
rm -f /usr/lib/lua/luci/view/admin_status/index/upnp.htm
rm -f /usr/lib/lua/luci/view/admin_status/index/ddns.htm
rm -f /usr/lib/lua/luci/view/admin_status/index/minidlna.htm

sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/aria2.lua
sed -i 's/services/nas/g' /usr/lib/lua/luci/view/aria2/overview_status.htm
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/hd_idle.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/samba.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/samba4.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/minidlna.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/transmission.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/mjpg-streamer.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/p910nd.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/usb_printer.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/xunlei.lua
sed -i 's/services/nas/g' /usr/lib/lua/luci/view/minidlna_status.htm

#ln -sf /sbin/ip /usr/bin/ip

#Openwrt Password: whoami
sed -i '/^root:/d' /etc/shadow
sed -i '1i\root:$1$fqGWXyoc$jcmp6mAm6Mj/OU.pbJi471:19541:0:99999:7:::' /etc/shadow

# Config Aura Opewnrt Package  Source;
sed -i '/check_signature/d' /etc/opkg.conf
sed -i "s/# //g" /etc/opkg/distfeeds.conf
sed -i '/openwrt_luci/ { s/snapshots/releases\/18.06.9/g; }' /etc/opkg/distfeeds.conf
sed -i 's#downloads.openwrt.org/snapshots#aurawrt.isoogo.com#g' /etc/opkg/distfeeds.conf

# Coofig Aura Opewnrt firewall.
sed -i '/REDIRECT --to-ports 53/d' /etc/firewall.user
#echo 'iptables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 53' >> /etc/firewall.user
#echo 'iptables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-ports 53' >> /etc/firewall.user
#echo '[ -n "$(command -v ip6tables)" ] && ip6tables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 53' >> /etc/firewall.user
#echo '[ -n "$(command -v ip6tables)" ] && ip6tables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-ports 53' >> /etc/firewall.user
#echo 'iptables -A OUTPUT -m string --string "api.installer.xiaomi.cn" --algo bm --to 65535 -j DROP' >> /etc/firewall.user
uci set firewall.@defaults[0].forward='ACCEPT'
uci commit firewall

sed -i '/option disabled/d' /etc/config/wireless
sed -i '/set wireless.radio${devidx}.disabled/d' /lib/wifi/mac80211.sh

sed -i '/DISTRIB_REVISION/d' /etc/openwrt_release
echo "DISTRIB_REVISION='V23.10.1'" >>/etc/openwrt_release
sed -i '/DISTRIB_DESCRIPTION/d' /etc/openwrt_release
echo "DISTRIB_DESCRIPTION='OpenWrt '" >>/etc/openwrt_release

sed -i '/log-facility/d' /etc/dnsmasq.conf
echo "log-facility=/dev/null" >>/etc/dnsmasq.conf

# Aura Openwrt drobear ssh public key Config.
cat <<"EOF" >>/etc/dropbear/authorized_keys
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDReconVNvAhM7MtKHL0G6iOikJbFJ5Yj5RJsFjQkH5q7mXgmXvoTna+PaVrijxo2yBtOqEvQddWExW/ETnaZP3wvYrKX8Al7lJLG/ntYu/QPHE56uG0itwLEJ0lib2dBYeATx5GAzg7Xh34VjHPvWw/4lb6V4n/n2T4w4807IlLwMGfF3+JWgjIX0dz/OD+LucFljj7Ig0MaLE5xbJMNtK3wTgQ1wHmpsUWftP6sHWeqBqzQHlJc4bihvoxVXEZumukGZ7h0lWyx9iKcSMvQXF/MYGnP8mubKSCHXhk6d8hSyC+UHROAM8IQFNR2WcK9on+nCFVMBLXThpMEaneo4nDcotZuWPTx+NgRpxAROJpJsCF5dP+JWFESrPdxgMIOk4l5+MVHHoJXAIstEhOn+8hVnWxxig4Lwa3E+v+9OPvWicLB6TG1NyBUqQV++sr6Lp9bhR8dBJ/QnM9HnooHVMGn9lZFjCcjaar6Xs9xoalb1/Gbb8UHnRJJHN10Lk47M=
EOF

rm -rf /tmp/luci-modulecache/
rm -f /tmp/luci-indexcache

exit 0
