# Copyright (C) 2016 Openwrt.org
#
# This is free software, licensed under the Apache License, Version 2.0 .
# Maintained by eSir Playground <https://github.com/esirplayground/luci-dbsn-init>

include $(TOPDIR)/rules.mk

PKG_NAME:=luci-aura-init
PKG_VERSION:=20240302
PKG_RELEASE:=1
LUCI_TITLE:=LuCI Support of RunShell Router
LUCI_PKGARCH:=all

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
